const mongoose= require("mongoose");
const commercialShopSchema = new mongoose.Schema({
    //Property Location
    city: {type: String, required: true},
    locality: {type: String, required: true},
    projectMarketName: {type: String},
    Address: {type: String, maxlength: 256},
    landZone: {type: String, enum:["Industrial","Commercial","Residential","Transport and Communication","Public Utilities","Public and Semi Public Use","Open Spaces","Agriculture Zone","Special Economic Zone","Natural Conservation Zone","Government Use"]},
    nearbyBusinesses: {type: String, enum:[
      "Agriculture Related",
      "Pets Store",
      "Bouquet",
      "Hair Salon",
      "Nursery",
      "Auto Components",
      "Automotive Components",
      "Auto",
      "Vehicle",
      "Vehicle Spare Parts",
      "Vehicle Service",
      "Auto Spare Parts",
      "Bike Spare Parts",
      "Bikes",
      "Motorcycle",
      "Cars",
      "Jeeps",
      "Car Spare Parts",
      "Automotive Maintenance and Repair",
      "Repair Automotive",
      "Animation and Gaming",
      "Game Parlour",
      "Electronic Games",
      "Gaming",
      "Pets and Related",
      "Flowers",
      "Pets Shop",
      "Pet Items",
      "Pets",
      "Veterinary",
      "Pet Hospital",
      "Hospital, Clinics, Biotechnology",
      "Hospital",
      "Clinic",
      "Pathology Lab",
      "Labs",
      "Cement",
      "Glass",
      "Bricks",
      "Tiles",
      "Wallpapers",
      "Ceramics",
      "Electronic Goods",
      "Consumer Durables",
      "Fridge",
      "AC",
      "Microwave",
      "Washing Machine",
      "Camera",
      "Laptops",
      "Computer Hardware",
      "Computers",
      "Geyser",
      "Wood",
      "Furniture",
      "Bed",
      "Sofa",
      "Almirah",
      "Cupboard",
      "Furniture and Related",
      "Bean Bags",
      "Mattresses",
      "Quilts",
      "Kitchen Goods and Related",
      "Kitchen items",
      "Containers",
      "Sieve",
      "Stove",
      "Cooker",
      "Crockery",
      "Dinner Set",
      "Plastic bottles",
      "Plastic Containers and Items",
      "Footwear/Leather",
      "Footwear",
      "Bags",
      "Sandals",
      "Purse",
      "Travel Bags",
      "Restaurant",
      "Snacks",
      "Sweet Shop",
      "Drinks",
      "Wine and Beer",
      "Wine",
      "Alcohol",
      "Beverages",
      "Juice",
      "Fruit Shakes",
      "Ice Cream",
      "Dosa",
      "Hotel",
      "Dhaba",
      "Gems and Jewellery",
      "Jewellers",
      "Gold",
      "Ornaments",
      "Necklace",
      "Artificial Jewellery",
      "Jewellery",
      "GoldSmith",
      "Handicrafts & Carpets",
      "Carpets",
      "Flower Pots",
      "Handicraft Items",
      "Handicraft",
      "Shawl",
      "Artifacts",
      "Clay Artifacts",
      "Showpiece",
      "IT/ITES/Call Center",
      "Call Center",
      "Customer Service",
      "Consulting",
      "Consultant",
      "Website Design",
      "Website",
      "Construction Related Services",
      "Contractor",
      "Architecture Services",
      "Architecture Planning",
      "Industrial Supplies and Related",
      "Industrial Supplies",
      "Raw Material",
      "Beauty, Spa, Saloon and Related",
      "Beauty Parlour",
      "Spa",
      "Massage",
      "Saloon",
      "Jacuzzi",
      "Seeds",
      "Hair Spa",
      "Hair Style",
      "Hair Styling",
      "Bridal Makeup",
      "Make up",
      "Wedding Make Up",
      "Groom Make Up",
      "Petrochemicals & Petroleum products",
      "Gas Pump",
      "Kerosene",
      "Petroleum Goods",
      "CNG Repair",
      "LPG Booking Office",
      "LPG",
      "Chemist",
      "Druggist",
      "Pharmaceuticals",
      "Pharmacy",
      "Power",
      "Solar Devices",
      "Solar Energy",
      "Renewable Energy",
      "Alternate Energy",
      "Fashion Brand",
      "Garments and Related",
      "Textiles",
      "Apparels",
      "Wool",
      "Shawls",
      "Suits",
      "Sarees",
      "Mens wear",
      "Stationary",
      "Books",
      "Gift Shop",
      "Cards",
      "Art and Craft",
      "Printing",
      "Publishing",
      "Hardware Shop",
      "Plumbing",
      "Paints",
      "Hammer and Similar tools",
      "Shipping",
      "Courier",
      "Transport Goods",
      "Logistics",
      "Educational/Coaching Institutes",
      "Coaching Institute",
      "Coaching",
      "Training",
      "Tuition",
      "Skill Development",
      "Real Estate Brokers",
      "Real Estate Agency",
      "Property Dealer",
      "Gym",
      "Club",
      "Fitness Centre",
      "Zumba",
      "Dance Class",
      "Dance Training",
      "Yoga",
      "Pranayama Centre",
      "Electronics - Mobile and related",
      "Mobile phones",
      "Laptops",
      "Computers",
      "Computer Repair",
      "Mobile Repair",
      "Electronic Goods",
      "Electronic spare parts",
      "Electronic Projects",
      "Tours, Travels and Related",
      "Travel Planning",
      "Taxi Services",
      "Tour Planners",
      "Wedding Planners",
      "City Guide",
      "City Planners",
      "Tax Services",
      "Legal Services",
      "Insurance Services",
      "Financial Services",
      "Chartered Accountant",
      "Company Secretary",
      "Ad Agency",
      "Hoardings and Billboards",
      "OOH",
      "Advertising",
      "Media",
      "Digital advertising",
      "Pamphlets",
      "Media Printing",
      "Banner Printing",
      "Flex board Printing",
      "Toys",
      "Baby Care",
      "Baby Products",
      "Baby Creche",
      "Creche",
      "Idols",
      "Religious goods",
      "Religious products",
      "Incense Sticks",
      "Internet Provider",
      "Cable provider",
      "Internet Service",
      "Cable Service",
      "Dish TV",
      "NGOs",
      "Charity Institute",
      "Charitable Trust",
      "ATMs",
      "Cake Shop",
      "Clothes and Garments",
      "School",
      "Grocery",
      "Tutorials",
      "Tuition Centre",
      "Cafe",
      "Bakery",
      "Fun Zone",
      "Play Zone",
      "Shoes",
      "Bank",
      "Banquet Hall",
      "Two Wheeler Showroom",
      "Vehicle Service Center",
      "Multiplex",
      "Medical Store",
      "Saree Shop",
      "Fastfood",
      "Bike Showroom",
      "Dentist",
      "Dental Clinic",
      "Photography",
      "Studio",
      "Milk Booth",
      "Opticals",
      "Opticians",
      "Electrical Goods",
      "Pizza",
      "Car Showroom",
      "Bar",
      "Disc",
      "Wine Shop",
      "Bar and Restaurant",
      "Play School",
      "Scientific Traders",
      "Sanitory Goods"
  ]},
    
    //Property Features
    floorNumber: {type: String, enum:["Lower Basement","Upper Basement","Ground","1", "2", "3","4"]},
    totalFloor: {type: Number, maxlength: 150},
    furnished: {type: String, enum: ["Furnished", "Unfurnished"]},
    cornerShop: {type: Boolean, default: false},
    mainRoadFacing: {type: Boolean, default: false},
    personalWashroom: {type: Boolean, default: false},
    pantryCafeteria: {type: String, enum:["Dry","Wet","Not Available"]},
    
    //Property Area
    coveredArea: { type: Number, required: true },
    plotArea: {type: Number},
    carpetArea: { type: Number, required: true },
    areaUnit: { type:String, enum:["Sq-ft","Sq-yrd","Sq-m","Acre","Bigha","Hectare","Marla","Kanal","Biswa1","Biswa2","Ground","Aankadam","Rood","Chatak","Kottah","Marla","Cent","Perch","Guntha","Are","Kuncham","Katha","Gaj","Killa"],required: true},
    entranceWidth: { type: Number},
    widthEntranceUnit: {type:String, enum:["ft","meters"]},
       
    //Transaction Type & Property Avialability
    possessionStatus: {type: String, enum: ["Ready To Move", "Under Construction"]},
    availableFromMonth: {type: String, enum:[]},
    availableFromYear: {type: Number, enum:[]},
    constructionAge: {type: String, enum: ["New Construction","1 year", "2 years", "3 years", "4 years","5 years", "5 to 10 years","10 to 15 years","15 to 20 years","20 to 30 years","Above 30 years"]},
    currentlyLeasedOut: {type: Boolean, default: false},
    assuredReturns: {type: Boolean, default: false},
    rateOfReturn: {type: Number},
        
    //Price Details
    expectedPrice: {type: Number, required: true},
    bookingAmount: {type: Number},
    priceNegotiable: {type: Boolean, default: false},
    
    //Others
    subPropertyType: {type: String, enum:["Ready to Move Office Space","Bare Shell Office Space","Office in IT Park/ SEZ"]},
    ownership: { type: String, enum: ["Freehold","Leasehold", "Power Of Attorney", "Co-operative Society"], required: true},
    floors: {type: Number},
    unitsPerFloor: {type: Number},
    transactionType: { type: String, enum: ["New Property","Resale"]},
    overlooking: {type: String, enum:["Pool","Garden/Park","Main Road"]},
    status: {type: String, enum: ["Ready To Move", "Under Construction"]},
    facing: {type: String, enum: ["North", "South", "West", "East","North - East","North - West", "South - West", "South - East"]},
    propertyAge: {type: String, enum: ["New Construction","Under Construction","1 year", "2 years", "3 years", "4 years","5 years", "5 to 10 years","10 to 20 years","20 to 30 years","30+ years"]},
    additionalRooms:{ type: String, enum:["Store Room","Puja Room","Servant Room"]},
    amenities: {type: [String], enum: ["Reserved Parking","Visitor Parking","Lift","Power Backup","Gas Pipeline","Park","Kids Play Area","Gymnasium","Swimming Pool","Club House","Air Conditioned","Vaastu Compliance","Internet/Wi-Fi","Security Personnel","CCTV Camera"], required: true},
});

const CommercialShop = mongoose.model("CommercialShop", commercialShopSchema);
module.exports = CommercialShop;
