github.com:
    users:
        Mahesh-Banduni:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: Mahesh-Banduni
